---
- name: Install packages required for a simple GUI
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - xorg-server
    - xf86-video-intel
    - xorg-xinit
    - lightdm-gtk-greeter
    - lightdm
    - i3

- name: Create xinitrc file
  template:
    src: .xinitrc
    dest: ~/.xinitrc

- name: Create xprofile file
  template:
    src: .xprofile
    dest: ~/.xprofile

- name: Enable lightdm
  service:
    name: lightm
    state: started
    enabled: yes
