---

- name: Install terminal
  become: true
  package:
    name: "{{ terminal_package }}"
    state: present

- name: Ensure config dir exists
  file:
    path: "{{ terminal_config_location | dirname }}"
    state: directory
    recurse: yes

- name: Create terminal config
  template:
    src: terminal_config.j2
    dest: "{{ terminal_config_location }}"
