---
- name: Install i3
  become: yes
  package:
    name: i3
    state: present

- name: Ensure i3 config directory exists
  file:
    path: "/home/{{ user }}/.config/i3/"
    state: directory
    recurse: yes
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0755

- name: Create i3 config
  template:
    src: .i3config.j2
    dest: "/home/{{ user }}/.config/i3/config"

- name: Install py3status
  become: true
  package:
    name: py3status
    state: present

- name: Ensure i3status directory exists
  file:
    path: "/home/{{ user }}/.config/i3status/"
    state: directory
    recurse: yes
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0755

- name: Create py3status config
  template:
    src: .py3status.config.j2
    dest: "/home/{{ user }}/.config/i3status/config"
