---

- name: Install terminal
  become: true
  package:
    name: {{ terminal_package }}
    state: present

- name: Create terminal config
  template:
    src: terminal_config.j2
    dest: "{{ terminal_config_location }}"
