---
- name: Install packages required for a simple GUI
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - xorg-server
    - xorg-xinit
    - lightdm-gtk-greeter
    - lightdm
    - i3-gaps

- name: Copy xinitrc file
  template:
    src: .xinitrc
    dest: ~/.xinitrc

- name: Copy xprofile file
  template:
    src: .xprofile
    dest: ~/.xprofile

