---
- name: Install touchpad drivers (Arch)
  package:
    name: "{{ item }}"
    state: present
  loop:
    - xorg-xinput
    - libinput
    - xf86-input-libinput
  when: ansible_os_family == 'Archlinux'

- name: Install touchpad drivers (non-Arch)
  package:
    name: "{{ item }}"
    state: present
  loop:
    - xinput
    - libinput-bin
    - xserver-xorg-input-libinput
  when: not ansible_os_family == 'Archlinux'

- name: Ensure xorg conf dir exists
  file:
    path: /etc/X11/xorg.conf.d/
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Copy touchpad config
  become: true
  template:
    src: touchpad.conf.j2
    dest: /etc/X11/xorg.conf.d/30-touchpad.conf
