---
- name: Install git
  become: true
  package:
    name:
      - git
      - tig
    state: present
      
- name: Create gitignore file
  template:
    src: .gitignore_global.j2
    dest: "/home/{{ user }}/.gitignore_global"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0755

- name: Create gitconfig
  template:
    src: .gitconfig.j2
    dest: "/home/{{ user }}/.gitconfig"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0755
