---
- include_vars: "{{ item }}"
  with_first_found:
    - "../vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version | int}}.yml"
    - "../vars/{{ ansible_distribution }}.yml"
    - "../vars/{{ ansible_os_family }}.yml"
    - "../vars/default.yml"

- name: Install development packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - docker
    - docker-compose
    - "{{ python_package }}"
    - python-pip
