---
- name: Load vars for development role
  include_vars:
    file: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
    - default.yml

- name: Install development packages
  become: true
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ packages }}"
