---
- name: Check yay is installed
  stat:
    path: /usr/bin/yay
  register: yay_installation

- name: Install yay
  block: 
  - name: Install dependencies
    become: true
    pacman:
      name:
        - fakeroot
        - go
        - git
      state: present

  - name: Download yay repo
    git:
      repo: https://aur.archlinux.org/yay.git
      dest: /tmp/yay_installer/

  - name: Install yay
    command: makepkg -si --noconfirm
    args:
      chdir: /tmp/yay_installer/
  always:
    - name: Remove temp yay download
      file:
        path: /tmp/yay_installer/
        state: absent
  when: not yay_installation.stat.exists
