---
- name: Install common packages
  become: true
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - git
    - tmux
    - htop
    - vim
    - zsh

- name: Install useful debugging tools
  become: true
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - htop
    - lsof
    - iotop
    - sysstat

- name: Checkout dotfiles repo
  git:
    repo: https://github.com/laxd/dotfiles
    dest: /tmp/dotfiles

- name: Copy dotfiles
  copy:
    remote_src: true
    src: "/tmp/dotfiles/{{ item }}"
    dest: "/home/{{ user }}/{{ item }}"
    owner: "{{ user }}"
    group: "{{ user }}"
  with_items:
    - ".vimrc"
    - ".zshrc"
    - ".gitignore_global"
    - ".gitconfig"

- name: Check if oh-my-zsh is installed
  stat:
    path: /home/{{ user }}/.oh-my-zsh
  register: ohmyzsh_dir

- name: Download oh-my-zsh installer
  get_url:
    url: https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh
    dest: /tmp/oh-my-zsh_installer.sh
  when: ohmyzsh_dir.stat.exists == false

- name: Install oh-my-zsh
  shell: /tmp/oh-my-zsh_installer.sh
  when: ohmyzsh_dir.stat.exists == false

- name: oh-my-zsh tidyup
  file:
    path: /tmp/oh-my-zsh_installer.sh
    state: absent
  when: ohmyzsh_dir.stat.exists == false

