---
- name: Install common packages
  become: true
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - git
    - openssh
    - tmux
    - htop
    - vim

- name: Checkout dotfiles repo
  git:
    repo: https://github.com/laxd/dotfiles
    dest: /tmp/dotfiles

- name: Copy dotfiles
  copy:
    remote_src: true
    src: "/tmp/dotfiles/{{ item }}"
    dest: "/home/{{ dotfile_user }}/{{ item }}"
    owner: "{{ dotfile_user }}"
    group: "{{ dotfile_user }}"
  with_items:
    - ".vimrc"
    - ".zshrc"
    - ".gitignore_global"
    - ".gitconfig"
