---
- name: Create user
  user:
    name: "{{ user }}"
    state: present

- name: Copy ssh key from local user
  authorized_key:
    user: "{{ user }}"
    state: present
    key: "{{ lookup('file', ssh_key_loc) }}"
  when: ssh_key_loc is defined
