---

- name: Ensure SSH is installed (Arch)
  become: true
  package:
    name: "{{ item }}"
    state: present
  loop:
    - openssh
    - mosh
  when: ansible_os_family == 'Archlinux'

- name: Ensure SSH is installed (non-Arch)
  become: true
  package:
    name: "{{ item }}"
    state: present
  loop:
    - ssh
    - mosh
  when: not ansible_os_family == 'Archlinux'

- name: Ensure ~/.ssh dir is present
  file:
    path: "/home/{{ user }}/.ssh"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0700

- name: Create SSH config file
  template:
    src: .ssh_config.j2
    dest: "/home/{{ user }}/.ssh/config"
    mode: 0700
