---

- name: Download PowerlineSymbols.otf
  get_url:
    url: https://github.com/powerline/powerline/raw/develop/font/PowerlineSymbols.otf
    dest: "/home/{{ user }}/.local/share/fonts/"
    mode: 0755
  notify: Clear font cache

- name: Create font config file
  template:
    src: 10-powerline-symbols.conf.j2
    dest: "/home/{{ user }}/.config/fontconfig/conf.d/"
