---
- name: Install zsh and dependencies
  become: true
  package:
    name:
      - zsh
      - neofetch
    state: present

- name: Check if oh-my-zsh is installed
  stat:
    path: /home/{{ user }}/.oh-my-zsh
  register: ohmyzsh_dir

- name: Install oh-my-zsh
  block:
  - name: Install git (required for oh-my-zsh installation)
    become: true
    package:
      name: git
      state: present

  - name: Download oh-my-zsh installer
    get_url:
      url: https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh
      dest: /tmp/oh-my-zsh_installer.sh
      mode: '0777'

  - name: Install oh-my-zsh
    command: /tmp/oh-my-zsh_installer.sh --unattended
    become: true
    become_user: "{{ user }}"

  - name: Remove oh-my-zsh installer
    file:
      path: /tmp/oh-my-zsh_installer.sh
      state: absent
  when: not ohmyzsh_dir.stat.exists

- name: Install zsh theme
  git:
    repo: https://github.com/bhilburn/powerlevel9k.git
    dest: "/home/{{ user }}/.oh-my-zsh/custom/themes/powerlevel9k"
    version: v0.6.7

- name: Copy .zshrc
  template:
    src: ".zshrc.j2"
    dest: "/home/{{ user }}/.zshrc"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0744"

- name: Change shell to ZSH
  become: true
  user:
    name: "{{ user }}"
    shell: /bin/zsh
    state: present
