---

- name: Install vim
  become: true
  package:
    name: vim
    state: present

- name: Copy .vimrc file
  template:
    src: .vimrc.j2
    dest: "/home/{{ user }}/.vimrc"

- name: Check vim plugins are installed
  stat:
    path: "/home/{{ user }}/.vim/bundle"
  register: vim_plugins

- name: Install vundle plugins
  block:
  - name: Create vim plugin directory
    file:
      path: "/home/{{ user }}/.vim/bundle"
      state: directory
      owner: "{{ user }}"
      group: "{{ user }}"
      mode: 0755

  - name: Install Vundle
    git:
      repo: "https://github.com/VundleVim/Vundle.vim/"
      dest: "/home/{{ user }}/.vim/bundle/Vundle.vim"
      update: no
      version: "v0.10.2"

  - name: Install vim plugins
    command: "vim +VundleInstall +qall"
  when: not vim_plugins.stat.exists
